### ISSUE TITLE
Alaska Topics/Resource Breadcrumbs Incorrect

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#991] opened 2019-09-10 19:51 UTC
When navigating through T/R to get to resources, the breadcrumbs do not display the correct navigation.  For example, user went to FAMILY-> Domestic Violence & Abuse -> Protective Orders -> Organizations -> Alaska Bar Association Lawyer Referral Service 

Once user clicks on Alaska Bar Assoc.... the breadcrumbs are as follows:

All Topics/Family/Mediation / Alternative Dispute Resolution/Organization

**Comment by KellyeDC-zz** [comment] 2019-09-10 19:52
<img width="861" alt="Breadcrumb defect" src="https://user-images.githubusercontent.com/45771252/64645445-eb952300-d3e2-11e9-93d9-c20da7d477c1.PNG">

**Comment by KellyeDC-zz** [comment] 2019-10-01 18:42
@yevhenobertas Is this issue resolved?

**Comment by grawdon** [comment] 2020-01-10 21:06
@KellyeDC @yevhenobertas @asaperski-gloriumtech This is still not fixed. When I click on an organization in Protective Orders the breadcrumb jumps to Issues for immigrants in Protective Order Cases. See below:
![image](https://user-images.githubusercontent.com/46725623/72186361-b57ca580-33ba-11ea-8296-ca74477367d3.png)
![image](https://user-images.githubusercontent.com/46725623/72186371-bca3b380-33ba-11ea-8d5b-7b46aa560f55.png)

**Comment by ozholob** [comment] 2020-01-15 09:11
Hi @grawdon, fixed on dev
![image](https://user-images.githubusercontent.com/55988406/72420615-ba10d780-3787-11ea-880e-225675d4f06f.png)
![image](https://user-images.githubusercontent.com/55988406/72420676-d44ab580-3787-11ea-98e3-1c26ab271da6.png)

**Comment by ozholob** [comment] 2020-01-15 10:34
Hi @grawdon, I could not reproduce that. It seems to be fixed on dev. Thanks
![image](https://user-images.githubusercontent.com/55988406/72426891-45439a80-3793-11ea-9e36-1e1bd3532d15.png)

**Comment by ozholob** [comment] 2020-01-15 13:32
Hi @grawdon, it's fixed on DEV
![image](https://user-images.githubusercontent.com/55988406/72437767-28679100-37ac-11ea-98a5-688600c9964d.png)
Thanks

**Comment by grawdon** [comment] 2020-01-22 20:41
@KellyeDC-zz When I tested two different organizations, the right breadcrumbs showed up both times. Appears to be fixed.

**Closed as completed** 2020-01-22 20:41 UTC
Labels: Bug, Glenn
